DATABASE='/var/www/housechores/chores.db'
DEBUG=False
DEBUG_TB_INTERCEPT_REDIRECTS=False
SECRET_KEY='thisisareallysecretkeydon7you71nk'
USERNAME='admin'
PASSWORD='admin'
LOGFILE = '/var/www/housechores/log.log'
LOGFILEMODE = 'w'
LOGFORMAT = '%(asctime)s - %(funcName)s from %(filename)s line: %(lineno)s - %(levelname)s: %(message)s'
LOGLEVEL = 'ERROR'
XMLEXPORT='/var/www/housechores/export/database_xml'
