DATABASE='chores.db'
DEBUG=True
DEBUG_TB_INTERCEPT_REDIRECTS=False
SECRET_KEY='thisisareallysecretkeydon7you71nk'
USERNAME='admin'
PASSWORD='admin'
LOGFILE = 'log.log'
LOGFILEMODE = 'w'
LOGFORMAT = '%(asctime)s - %(funcName)s from %(filename)s line: %(lineno)s - %(levelname)s: %(message)s'
LOGLEVEL = 'DEBUG'
XMLEXPORT='export/database_xml'
